package com.springboot.mypractice.entities;

import java.math.BigDecimal;
import java.util.Date;

public class PurchaseRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.sum
     *
     * @mbggenerated
     */
    private BigDecimal sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.purchase_date
     *
     * @mbggenerated
     */
    private Date purchaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Purchase_Record.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.id
     *
     * @return the value of Purchase_Record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.id
     *
     * @param id the value for Purchase_Record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.user_id
     *
     * @return the value of Purchase_Record.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.user_id
     *
     * @param userId the value for Purchase_Record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.product_id
     *
     * @return the value of Purchase_Record.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.product_id
     *
     * @param productId the value for Purchase_Record.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.price
     *
     * @return the value of Purchase_Record.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.price
     *
     * @param price the value for Purchase_Record.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.quantity
     *
     * @return the value of Purchase_Record.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.quantity
     *
     * @param quantity the value for Purchase_Record.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.sum
     *
     * @return the value of Purchase_Record.sum
     *
     * @mbggenerated
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.sum
     *
     * @param sum the value for Purchase_Record.sum
     *
     * @mbggenerated
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.purchase_date
     *
     * @return the value of Purchase_Record.purchase_date
     *
     * @mbggenerated
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.purchase_date
     *
     * @param purchaseDate the value for Purchase_Record.purchase_date
     *
     * @mbggenerated
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Purchase_Record.note
     *
     * @return the value of Purchase_Record.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Purchase_Record.note
     *
     * @param note the value for Purchase_Record.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}