package com.springboot.mypractice.dao;

import com.springboot.mypractice.entities.PurchaseRecord;

public interface PurchaseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Purchase_Record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Purchase_Record
     *
     * @mbggenerated
     */
    int insert(PurchaseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Purchase_Record
     *
     * @mbggenerated
     */
    int insertSelective(PurchaseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Purchase_Record
     *
     * @mbggenerated
     */
    PurchaseRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Purchase_Record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PurchaseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Purchase_Record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PurchaseRecord record);
}